### ISSUE TITLE
Sobre ser um desenvolvedor de software

### ISSUE THREAD

**Issue by sergiokopplin** [marceloogeda/tech-hour#4]
O desenvolvedor é o profissional que escreve os códigos para construir as aplicações.

[GIFS](https://giphy.com/search/coding) para usar
Sobre ser um programador: https://media.giphy.com/media/srbiWWa0VW2YM/giphy.gif

Exemplo de tela:

![image](https://cloud.githubusercontent.com/assets/2743180/25409368/01844864-29e8-11e7-9126-eb38fde1a37f.png)

Código fonte html:

![image](https://cloud.githubusercontent.com/assets/2743180/25409584/e7674c6e-29e8-11e7-8a39-dca3f0773777.png)

ref: 

- [itforum 365](http://www.itforum365.com.br/carreira/entenda-o-que-faz-um-desenvolvedor)

**Comment by marceloogeda** [comment]
Não encontrei uma forma legal para abordar o assunto.
