### ISSUE TITLE
Tela Catho / Screenshot + código fonte

### ISSUE THREAD

**Issue by sergiokopplin** [marceloogeda/tech-hour#6]
Tela:
![image](https://cloud.githubusercontent.com/assets/2743180/25409917/710fb450-29ea-11e7-8190-20a0b7a1a045.png)

Podemos fazer um slide depois mostrando o que são os componentes nessa tela, tipo com retângulos vermelhos em volta, tipo isso (na tela):

![image](https://cloud.githubusercontent.com/assets/2743180/25409946/93058de6-29ea-11e7-9d46-8a12f5ca38b3.png)

Depois mostramos o código e fazemos o mesmo, o que acha?

Código fonte do card do médico:

![image](https://cloud.githubusercontent.com/assets/2743180/25409997/d6f32720-29ea-11e7-9e97-7f417b87c229.png)

Podemos depois colocar os retângulos apontando para o label do título por exemplo e mostrando na tela que o código representa algo na tela de verdade

Exemplo:
![image](https://cloud.githubusercontent.com/assets/2743180/25410126/6b0657b6-29eb-11e7-87d0-20f779619488.png)
![image](https://cloud.githubusercontent.com/assets/2743180/25410144/76db2490-29eb-11e7-8508-e1c5bb52a5c8.png)

**Comment by marceloogeda** [comment]
![screencapture-catho-br-vagas-1493209115514](https://cloud.githubusercontent.com/assets/3205036/25434236/e6ad6b04-2a61-11e7-9a56-dbcb4c765a58.png)

**Comment by sergiokopplin** [comment]
done!
