### ISSUE TITLE
Slide Representação dos componentes

### ISSUE THREAD

**Issue by marceloogeda** [marceloogeda/tech-hour#7]
Poderiamos fazer algo desse tipo, o que acha? 

![screen shot 2017-04-26 at 9 38 02 am](https://cloud.githubusercontent.com/assets/3205036/25434789/180dab3a-2a64-11e7-91b3-256122ef5f49.png)

ref:
https://docs.google.com/presentation/d/1WnYsxRMiNEArT3xz7xXHdKeH1C-jT92VxmptghJb5Es/edit#slide=id.p

**Comment by sergiokopplin** [comment]
![image](https://cloud.githubusercontent.com/assets/2743180/25447805/e753cf6e-2a8c-11e7-82e1-acba37eac797.png)

**Comment by sergiokopplin** [comment]
![e753cf6e 2a8c 11e7 82e1 acba37eac797 png 1288x928](https://cloud.githubusercontent.com/assets/2743180/25448170/faa62c82-2a8d-11e7-98f8-f8f0f2bd532f.png)

**Comment by sergiokopplin** [comment]
![image](https://cloud.githubusercontent.com/assets/2743180/25448215/21242bd4-2a8e-11e7-9aa1-26b54361982c.png)

**Comment by sergiokopplin** [comment]
![image](https://cloud.githubusercontent.com/assets/2743180/25448245/370ebfcc-2a8e-11e7-9489-57cbee0cb260.png)
